# Generated by Django 5.0.2 on 2024-03-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('access_type', models.CharField(max_length=10)),
                ('fullname', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='AdminToken_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=40, unique=True)),
                ('username', models.CharField(max_length=30)),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HealthcardTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='', max_length=40)),
                ('healthcard_number', models.CharField(max_length=20, unique=True)),
                ('mobile_number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.CharField(max_length=20)),
                ('mailid', models.CharField(max_length=40, null=True)),
                ('address', models.TextField()),
                ('insurance', models.CharField(max_length=40)),
                ('profile_img', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='TokenTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=40, unique=True)),
                ('mobile_number', models.CharField(max_length=10)),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UsersTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=10, unique=True)),
                ('fullname', models.CharField(max_length=100)),
            ],
        ),
    ]
